name: Sync Merged PR to GitHub.com (via SSH)

on:
  pull_request:
    types: [closed]

jobs:
  sync-pr-merge:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    env:
      GHEC_REPO: git@github.com:thoughtspot/${{ github.event.repository.name }}.git

    steps:
      - name: Log sync initiation
        run: |
          echo "Initiating sync for PR #${{ github.event.pull_request.number }} to branch ${{ github.event.pull_request.base.ref }}"
          echo "Repository: ${{ github.event.repository.name }}"

      - name: Set up SSH access to GitHub.com
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GHEC_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        continue-on-error: false

      - name: Checkout source repo (internal GHE)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set env variables
        run: |
          echo "TARGET_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "MERGE_SHA=${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_ENV

      - name: Create squashed commit from merged PR
        run: |
          git config user.name "jagannath-sahu-ts"
          git config user.email "jagannath.sahu@thoughtspot.com"
          git config url."git@github.com:".insteadOf "https://github.com/"
          
          # Debug info
          echo "Current git status:"
          git status
          
          echo "Recent commits:"
          git log -n 5 --oneline
          
          # Pull the latest changes to ensure we have the merge commit
          git pull origin ${TARGET_BRANCH} --ff-only
          
          # Find the PR merge commit by looking at recent history
          echo "Looking for PR merge commit in history..."
          PR_MERGE_COMMIT=$(git log -n 20 --grep="Merge pull request #${PR_NUMBER}" --format="%H")
          
          if [ -z "$PR_MERGE_COMMIT" ]; then
            echo "Could not find merge commit for PR #${PR_NUMBER} in recent history."
            echo "Trying alternative approach with GitHub provided merge SHA..."
            PR_MERGE_COMMIT="${MERGE_SHA}"
          fi
          
          echo "Using merge commit: ${PR_MERGE_COMMIT}"
          
          # Create a temporary branch for our changes
          git checkout -b temp-sync-branch
          
          # Identify the parent commit before the merge (on the target branch)
          PARENT_COMMIT=$(git log -n 1 "${PR_MERGE_COMMIT}^1" --format="%H")
          echo "Parent commit before merge: ${PARENT_COMMIT}"
          
          # Find all the files that were changed in the PR
          echo "Getting list of changed files between parent and merge commit..."
          CHANGED_FILES=$(git diff --name-only ${PARENT_COMMIT} ${PR_MERGE_COMMIT})
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected between parent and merge commit."
            echo "Trying direct diff with PR number..."
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "Still no changes detected. This might be an empty PR or an issue with git history."
            echo "Creating empty commit to continue workflow..."
            git commit --allow-empty -m "Sync ${TARGET_BRANCH} from internal (PR #${PR_NUMBER}) - No changes detected"
            exit 0
          fi
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Reset to the state before the merge
          git reset --hard ${PARENT_COMMIT}
          
          # For each changed file, copy it from the merge commit
          echo "Creating squashed changes..."
          for FILE in $CHANGED_FILES; do
            echo "Processing: $FILE"
            DIR=$(dirname "$FILE")
            if [ "$DIR" != "." ]; then
              mkdir -p "$DIR" 2>/dev/null || true
            fi
            
            # Check if file exists in merge commit
            if git show ${PR_MERGE_COMMIT}:"$FILE" &>/dev/null; then
              echo "  - Copying file from merge commit"
              git show ${PR_MERGE_COMMIT}:"$FILE" > "$FILE"
            else
              echo "  - File was deleted in PR, removing"
              rm -f "$FILE" 2>/dev/null || true
            fi
          done
          
          # Stage all changes
          git add -A
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit after processing files. Creating empty commit."
            git commit --allow-empty -m "Sync ${TARGET_BRANCH} from internal (PR #${PR_NUMBER}) - No changes detected"
          else
            echo "Changes detected, creating commit"
            git commit -m "Sync ${TARGET_BRANCH} from internal (PR #${PR_NUMBER})"
          fi
        continue-on-error: false

      - name: Add GitHub.com as remote
        run: |
          echo "Adding GitHub.com as remote 'public'..."
          git remote add public $GHEC_REPO
          
          echo "Fetching from public remote..."
          git fetch public ${TARGET_BRANCH} || echo "Target branch does not exist on GitHub.com (will be created)"
        continue-on-error: false

      - name: Check for conflicts on destination
        id: conflict_check
        run: |
          echo "Checking for potential conflicts..."
          DEST_HEAD=$(git rev-parse public/${TARGET_BRANCH} 2>/dev/null || echo "none")
          
          if [ "$DEST_HEAD" != "none" ]; then
            echo "Destination branch exists. Checking for conflicts..."
            if git merge-base --is-ancestor $DEST_HEAD HEAD; then
              echo "No conflict detected. Safe to sync."
              echo "conflict_detected=false" >> $GITHUB_OUTPUT
            else
              echo "WARNING: Conflict detected. Aborting sync to prevent data loss."
              echo "conflict_detected=true" >> $GITHUB_OUTPUT
              exit 1
            fi
          else
            echo "Destination branch doesn't exist. Will create it."
            echo "conflict_detected=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: false

      - name: Backup GitHub.com branch (if exists)
        if: steps.conflict_check.outputs.conflict_detected == 'false'
        run: |
          echo "Creating backup of existing branch (if any)..."
          if git show-ref --verify --quiet refs/remotes/public/${TARGET_BRANCH}; then
            echo "Creating backup branch: backup-before-sync-${TARGET_BRANCH}-${TIMESTAMP}"
            git push public public/${TARGET_BRANCH}:refs/heads/backup-before-sync-${TARGET_BRANCH}-${TIMESTAMP}
            echo "Backup created successfully."
          else
            echo "No existing branch to backup."
          fi
        continue-on-error: true

      - name: Force push squashed commit to GitHub.com
        if: steps.conflict_check.outputs.conflict_detected == 'false'
        run: |
          echo "Pushing squashed commit to GitHub.com..."
          if ! git push --force public HEAD:${TARGET_BRANCH}; then
            echo "::error::Failed to push to public repository"
            exit 1
          fi
          echo "Successfully pushed to ${TARGET_BRANCH} on public repository"
        continue-on-error: false

      - name: Post sync status
        if: steps.conflict_check.outputs.conflict_detected == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Changes from PR #${{ github.event.pull_request.number }} have been successfully synced to the public repository on branch `${{ github.event.pull_request.base.ref }}`'
            })
        continue-on-error: true

      - name: Notify if sync failed due to conflicts
        if: failure() && steps.conflict_check.outputs.conflict_detected == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Failed to sync changes to the public repository due to potential conflicts. Manual intervention required.'
            })
        continue-on-error: true
